esphome:
  name: esphome-web-cfx3
  friendly_name: ESPHome Dometic CFX3 WiFi
  min_version: 2025.5.0

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  source: github://andrewbackway/esphome-dometic_cfx_ble@main
   refresh: 1s

web_server:
  version: 3

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

dometic_cfx_ble:
  id: dometic_cfx_ble1
  mac_address: "AA:BB:CC:DD:EE:FF"
  product_type: DZ  # or SZI, SZ

sensor:
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: COMPARTMENT_0_MEASURED_TEMPERATURE
    name: "CFX Zone 1 Temp"
    unit_of_measurement: "째C"
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: COMPARTMENT_1_MEASURED_TEMPERATURE
    name: "CFX Zone 2 Temp"
    unit_of_measurement: "째C"
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: BATTERY_VOLTAGE_LEVEL
    name: "CFX Battery Voltage"
    unit_of_measurement: "V"

switch:
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: COOLER_POWER
    name: "CFX Power"
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: COMPARTMENT_0_POWER
    name: "CFX Zone 1 Power"
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: COMPARTMENT_1_POWER
    name: "CFX Zone 2 Power"

number:
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: COMPARTMENT_0_SET_TEMPERATURE
    name: "CFX Zone 1 Set Temp"
    unit_of_measurement: "째C"
    min_value: -20
    max_value: 10
    step: 0.1
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: COMPARTMENT_1_SET_TEMPERATURE
    name: "CFX Zone 2 Set Temp"
    unit_of_measurement: "째C"
    min_value: -20
    max_value: 10
    step: 0.1

binary_sensor:
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: DOOR_ALERT
    name: "CFX Door Alert"
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: COMPARTMENT_0_DOOR_OPEN
    name: "CFX Zone 1 Door Open"  
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: COMPARTMENT_1_DOOR_OPEN
    name: "CFX Zone 2 Door Open"
    

text_sensor:
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: id(dometic_cfx_ble1)
    type: DEVICE_NAME
    name: "CFX Device Name"